on:
  push:
    tags: "v*"
  release:
    types: [published]

jobs:
  add_release_asset:
    runs-on: ubuntu-latest
    name: A job to add a release asset with submodules
    steps:
      - id: release-asset
        uses: yashpatel6/myactions/add-source-with-submodules@v5
